name: 'List packages'

on: [push]

jobs:

  list:
    name: List packages
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-24.04

    steps:

    - run: apt list --installed

    - run: apt-mark showmanual
